### ISSUE TITLE
My Sonar not available for CentOS 6

### ISSUE THREAD

**Issue by cescoffier** [hgomez/devops-incubator#16]
The MySonar is not available for CentOS 6. 

After having discussed with @hgomez, the main issue is the lack of Java on CentOS. It's even more critical on recent Sonar where the findbugs 3 plugin requires Java 7 to analyze Java 8 bytecode. (the `wrapper.conf` file must be modified to use a Java 7 / 8 JVM).

**Comment by hgomez** [comment]
I'll focus my effort on CentOS 7 and openSUSE now, so don't expect CentOS 6 support for MySonar :(
